comment:
  layout: "header, diff, components"

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true # Don't gate PRs based on Codecov passing thresholds

ignore:
  - "src/types"