#!/bin/bash

# This script drops you into a mysql shell.

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $THIS_DIR/common

if [ -n "$RUNNING_CONTAINER" ]; then 
  echo "Using $CONTAINER_NAME"
  docker exec -it $CONTAINER_NAME mysql --password=$DB_PASSWORD
else
  echo "$CONTAINER_NAME is not currently running, use the start-mysql command first"
fi