#!/bin/bash

# This script contains variables used in all of the other scripts in this directory

# neckbeard bash used to get the value of _this_ directory.
THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

CONTAINER_NAME=dwn-mysql
RUNNING_CONTAINER=$(docker ps -aq --filter name=$CONTAINER_NAME --filter status=running)
STOPPED_CONTAINER=$(docker ps -aq --filter name=$CONTAINER_NAME --filter status=exited)

# variables with defaults. these are overridden by our deployment infra in staging and prod
: ${DB_USER:="root"}
: ${DB_PASSWORD:="dwn"}
: ${DB_HOST:="localhost"}
: ${DB_PORT:="3306"}
: ${DB_NAME:="dwn"}

# colors that can be used in bash scripts when echoing
YELLOW='\033[33m'
RESET='\033[0m'