#! /bin/bash

# this script starts dockerized postgres if it isn't already running.

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $THIS_DIR/common

if [ -n "$RUNNING_CONTAINER" ]; then
  echo "Container $CONTAINER_NAME is already running"
elif [ -n "$STOPPED_CONTAINER" ]; then
  echo "Starting $CONTAINER_NAME"
  docker start $CONTAINER_NAME
else
  echo "Creating & starting $CONTAINER_NAME"
  docker run --detach \
    --name $CONTAINER_NAME \
    --env POSTGRES_DB=$DB_NAME \
    --env POSTGRES_USER=$DB_USER \
    --env POSTGRES_PASSWORD=$DB_PASSWORD \
    --env POSTGRES_INITDB_ARGS='--lc-collate=C --lc-ctype=C' \
    --publish $DB_PORT:$DB_PORT \
    postgres:13.3
fi
