#! /bin/bash

# This script stops dockerized postgres if it isn't already running. passing -rm will delete the 
# container as well

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $THIS_DIR/common

if [ -z "$STOPPED_CONTAINER" ]; then
  echo "stopping $CONTAINER_NAME"
  docker container stop $CONTAINER_NAME
fi

if [[ " $* " =~ " -rm " ]]; then
  echo "Removing $CONTAINER_NAME"
  docker rm $CONTAINER_NAME
fi